name: CI

on:
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Vitest
        run: pnpm test:unit

      - name: Install Webkit dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwoff1 libopus0 libwebpdemux2 libwebp6 libwebpmux3 libgstreamer-plugins-base1.0-0 libxslt1.1 libegl1 libgles2 gstreamer1.0-plugins-base gstreamer1.0-plugins-good libharfbuzz0b libhyphen0 libicu67 libcairo2 libpango-1.0-0 libpangoft2-1.0-0
          npx playwright install-deps webkit

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright
        run: pnpm test:e2e

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
